import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@mikro-orm/nestjs';
import { EntityManager, EntityRepository, FilterQuery } from '@mikro-orm/mysql';
import { Category } from 'src/database/entities/category.entity';
import { CreateCategoryDto } from './dto/create-category.dto';
import { UpdateCategoryDto } from './dto/update-category.dto';
import { CategoryQueryDto } from './dto/category-query.dto';
import { UploadService } from '../upload/upload.service';

@Injectable()
export class CategoriesService {
  constructor(
    @InjectRepository(Category)
    private readonly categoryRepository: EntityRepository<Category>,
    private readonly em: EntityManager,
    private readonly uploadService: UploadService,
  ) {}

  async findAll(query: CategoryQueryDto) {
    const {
      page = 1,
      limit = 10,
      search,
      parent_id,
      is_active,
      include_children = false,
      include_products = false,
    } = query;
    const offset = (page - 1) * limit;

    const where: FilterQuery<Category> = {};

    if (search) {
      where.$or = [
        { name: { $like: `%${search}%` } },
        { slug: { $like: `%${search}%` } },
      ];
    }

    if (parent_id !== undefined) {
      where.parent = parent_id;
    }

    if (is_active !== undefined) {
      where.isActive = is_active;
    }

    const populate: any[] = ['parent'];
    if (include_children) {
      populate.push('children');
    }
    if (include_products) {
      populate.push('products');
    }

    const [items, total] = await this.categoryRepository.findAndCount(where, {
      limit,
      offset,
      populate,
      orderBy: { sortOrder: 'ASC', createdAt: 'DESC' },
    });

    return {
      items,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  async findOne(idOrSlug: number | string) {
    let category;
    if (typeof idOrSlug === 'number' || /^\d+$/.test(String(idOrSlug))) {
      category = await this.categoryRepository.findOne(Number(idOrSlug), {
        populate: ['parent', 'children', 'products'],
      });
    } else {
      category = await this.categoryRepository.findOne({ slug: String(idOrSlug) } as any, {
        populate: ['parent', 'children', 'products'],
      });
    }

    if (!category) {
      throw new NotFoundException(`Category with ID/slug '${idOrSlug}' not found`);
    }

    return category;
  }

  async findTree() {
    // Get all root categories (no parent)
    const rootCategories = await this.categoryRepository.find(
      { parent: null },
      {
        populate: ['children'],
        orderBy: { sortOrder: 'ASC', name: 'ASC' },
      },
    );

    return rootCategories;
  }

  async create(dto: CreateCategoryDto, file?: Express.Multer.File) {
    return await this.em.transactional(async (em) => {
      // Check if parent exists
      if (dto.parent_id) {
        const parent = await em.findOne(Category, dto.parent_id);
        if (!parent) {
          throw new NotFoundException(
            `Parent category with ID ${dto.parent_id} not found`,
          );
        }
      }

      // Upload image if provided
      let imageUrl: string | undefined;
      if (file) {
        imageUrl = await this.uploadService.uploadFile(file, 'categories');
      }

      const category = em.create(Category, {
        name: dto.name,
        slug: '', // Will be auto-generated by entity hook
        description: dto.description,
        parent: dto.parent_id
          ? em.getReference(Category, dto.parent_id)
          : undefined,
        image: imageUrl,
        isActive: dto.is_active ?? true,
        sortOrder: dto.sort_order ?? 0,
        metaTitle: dto.meta_title,
        metaDescription: dto.meta_description,
        metaKeywords: dto.meta_keywords,
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      // Slug will be auto-generated by the entity hook
      await em.persistAndFlush(category);
      return category;
    });
  }

  async update(id: number, dto: UpdateCategoryDto, file?: Express.Multer.File) {
    return await this.em.transactional(async (em) => {
      const category = await em.findOne(Category, id);

      if (!category) {
        throw new NotFoundException(`Category with ID ${id} not found`);
      }

      // Check if parent exists and prevent circular reference
      if (dto.parent_id !== undefined) {
        if (dto.parent_id === id) {
          throw new BadRequestException('Category cannot be its own parent');
        }
        if (dto.parent_id) {
          const parent = await em.findOne(Category, dto.parent_id);
          if (!parent) {
            throw new NotFoundException(
              `Parent category with ID ${dto.parent_id} not found`,
            );
          }
          category.parent = parent;
        } else {
          category.parent = undefined;
        }
      }

      // Update fields
      if (dto.name !== undefined) {
        category.name = dto.name;
        // Slug will be regenerated by the entity hook
        category.slug = ''; // Reset to trigger regeneration
      }
      if (dto.description !== undefined) category.description = dto.description;
      if (dto.is_active !== undefined) category.isActive = dto.is_active;
      if (dto.sort_order !== undefined) category.sortOrder = dto.sort_order;
      if (dto.meta_title !== undefined) category.metaTitle = dto.meta_title;
      if (dto.meta_description !== undefined)
        category.metaDescription = dto.meta_description;
      if (dto.meta_keywords !== undefined)
        category.metaKeywords = dto.meta_keywords;

      // Handle image upload
      if (file) {
        // Delete old image if exists
        if (category.image) {
          await this.uploadService.deleteFile(category.image);
        }
        category.image = await this.uploadService.uploadFile(
          file,
          'categories',
        );
      }

      await em.flush();
      return category;
    });
  }

  async remove(id: number) {
    const category = await this.categoryRepository.findOne(id, {
      populate: ['children', 'products'],
    });

    if (!category) {
      throw new NotFoundException(`Category with ID ${id} not found`);
    }

    // Check if category has children
    if (category.children.length > 0) {
      throw new BadRequestException(
        'Cannot delete category with child categories',
      );
    }

    // Delete image from MinIO if exists
    if (category.image) {
      await this.uploadService.deleteFile(category.image);
    }

    await this.em.removeAndFlush(category);
    return { success: true };
  }

  async uploadImage(id: number, file: Express.Multer.File) {
    const category = await this.categoryRepository.findOne(id);

    if (!category) {
      throw new NotFoundException(`Category with ID ${id} not found`);
    }

    // Delete old image if exists
    if (category.image) {
      await this.uploadService.deleteFile(category.image);
    }

    // Upload new image
    category.image = await this.uploadService.uploadFile(file, 'categories');
    await this.em.flush();

    return { image: category.image };
  }

  async removeImage(id: number) {
    const category = await this.categoryRepository.findOne(id);

    if (!category) {
      throw new NotFoundException(`Category with ID ${id} not found`);
    }

    if (!category.image) {
      throw new BadRequestException('Category has no image');
    }

    // Delete image from MinIO
    await this.uploadService.deleteFile(category.image);
    category.image = undefined;
    await this.em.flush();

    return { success: true };
  }
}
