name: CI/CD APPLICATION

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy-runner:
    runs-on: self-hosted   # chạy trên self-hosted runner

    environment: ecommerce
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan Sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=ecommerce-backend-production \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN