import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@mikro-orm/nestjs';
import { EntityManager, EntityRepository, FilterQuery } from '@mikro-orm/mysql';
import { Tag } from 'src/database/entities/tag.entity';
import { CreateTagDto } from './dto/create-tag.dto';
import { UpdateTagDto } from './dto/update-tag.dto';
import { TagQueryDto } from './dto/tag-query.dto';

@Injectable()
export class TagsService {
  constructor(
    @InjectRepository(Tag)
    private readonly tagRepository: EntityRepository<Tag>,
    private readonly em: EntityManager,
  ) {}

  async findAll(query: TagQueryDto) {
    const { page = 1, limit = 10, search } = query;
    const offset = (page - 1) * limit;

    const where: FilterQuery<Tag> = {};

    if (search) {
      where.name = { $like: `%${search}%` };
    }

    const [items, total] = await this.tagRepository.findAndCount(where, {
      limit,
      offset,
      orderBy: { name: 'ASC' },
    });

    return {
      items,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  async findOne(idOrSlug: number | string) {
    let tag;
    if (typeof idOrSlug === 'number' || /^\d+$/.test(String(idOrSlug))) {
      tag = await this.tagRepository.findOne(Number(idOrSlug), {
        populate: ['posts'],
      });
    } else {
      tag = await this.tagRepository.findOne({ slug: String(idOrSlug) } as any, {
        populate: ['posts'],
      });
    }

    if (!tag) {
      throw new NotFoundException(`Tag with ID/slug '${idOrSlug}' not found`);
    }

    return tag;
  }

  async create(dto: CreateTagDto) {
    // Check if tag with same name already exists
    const existing = await this.tagRepository.findOne({ name: dto.name });
    if (existing) {
      throw new BadRequestException(
        `Tag with name "${dto.name}" already exists`,
      );
    }

    const tag = this.em.create(Tag, {
      name: dto.name,
      slug: '', // Will be auto-generated by entity hook
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    await this.em.persistAndFlush(tag);
    return tag;
  }

  async update(id: number, dto: UpdateTagDto) {
    const tag = await this.tagRepository.findOne(id);

    if (!tag) {
      throw new NotFoundException(`Tag with ID ${id} not found`);
    }

    if (dto.name !== undefined) {
      // Check if another tag with same name exists
      const existing = await this.tagRepository.findOne({
        name: dto.name,
        id: { $ne: id },
      });
      if (existing) {
        throw new BadRequestException(
          `Tag with name "${dto.name}" already exists`,
        );
      }

      tag.name = dto.name;
      tag.slug = ''; // Reset to trigger regeneration
    }

    await this.em.flush();
    return tag;
  }

  async remove(id: number) {
    const tag = await this.tagRepository.findOne(id);

    if (!tag) {
      throw new NotFoundException(`Tag with ID ${id} not found`);
    }

    await this.em.removeAndFlush(tag);
    return { success: true };
  }
}
