import { EntityManager } from '@mikro-orm/core';
import { Seeder } from '@mikro-orm/seeder';
import { Post } from '../entities/post.entity';
import { User } from '../entities/user.entity';
import { Topic } from '../entities/topic.entity';
import { Tag } from '../entities/tag.entity';
import slugify from 'slugify';

export class PostSeeder extends Seeder {
  async run(em: EntityManager): Promise<void> {
    // Get admin user as author
    const admin = await em.findOne(User, { email: process.env.EMAIL_ADMIN });
    if (!admin) {
      console.log('- Admin user not found, skipping post seeding');
      return;
    }

    // Ensure Topics exist
    const jsTopic = await this.getOrCreateTopic(em, 'JavaScript', 'Programming related to JS');
    const tsTopic = await this.getOrCreateTopic(em, 'TypeScript', 'Typed superset of JS');
    const nestTopic = await this.getOrCreateTopic(em, 'NestJS', 'Node.js framework');
    const aiTopic = await this.getOrCreateTopic(em, 'AI & Machine Learning', 'Artificial Intelligence');
    const lifeTopic = await this.getOrCreateTopic(em, 'Lifestyle', 'Daily life and health');

    // Ensure Tags exist
    const tutorialTag = await this.getOrCreateTag(em, 'tutorial');
    const beginnerTag = await this.getOrCreateTag(em, 'beginner');
    const advancedTag = await this.getOrCreateTag(em, 'advanced');
    const newsTag = await this.getOrCreateTag(em, 'news');

    // Create sample posts
    await this.createPost(em, {
      title: 'Getting Started with NestJS',
      excerpt: 'Learn the basics of NestJS framework for building scalable server-side applications',
      content: `NestJS is a progressive Node.js framework... (Full content placeholder)`,
      author: admin,
      topics: [jsTopic, tsTopic, nestTopic],
      tags: [tutorialTag, beginnerTag],
      isPublished: true,
      publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
    });

    await this.createPost(em, {
      title: '10 Tips for Healthier Life',
      excerpt: 'Simple daily habits to improve your wellbeing.',
      content: 'Drinking water, sleeping well, and exercising...',
      author: admin,
      topics: [lifeTopic],
      tags: [beginnerTag],
      isPublished: true,
      publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    });

    await this.createPost(em, {
      title: 'The Future of AI',
      excerpt: 'How Artificial Intelligence is reshaping our world.',
      content: 'AI is everywhere nowadays...',
      author: admin,
      topics: [aiTopic],
      tags: [newsTag, advancedTag],
      isPublished: false,
      publishedAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // Scheduled
    });

    await this.createPost(em, {
      title: 'Advanced TypeScript Types',
      excerpt: 'Deep dive into conditional types and mapped types.',
      content: 'Let\'s explore the power of TS type system...',
      author: admin,
      topics: [tsTopic],
      tags: [advancedTag, tutorialTag],
      isPublished: true,
      publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    });

    await em.flush();
    console.log('✓ Posts seeded successfully');
  }

  private async getOrCreateTopic(em: EntityManager, name: string, description: string): Promise<Topic> {
    const existing = await em.findOne(Topic, { name });
    if (existing) return existing;

    const topic = em.create(Topic, {
      name,
      slug: slugify(name, { lower: true }),
      description,
      level: 0,
      isActive: true,
      sortOrder: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    em.persist(topic);
    return topic;
  }

  private async getOrCreateTag(em: EntityManager, name: string): Promise<Tag> {
    const existing = await em.findOne(Tag, { name });
    if (existing) return existing;

    const tag = em.create(Tag, {
      name,
      slug: slugify(name, { lower: true }),
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    em.persist(tag);
    return tag;
  }

  private async createPost(
    em: EntityManager,
    data: {
      title: string;
      excerpt: string;
      content: string;
      author: User;
      topics: Topic[];
      tags: Tag[];
      isPublished: boolean;
      publishedAt: Date;
    },
  ): Promise<Post> {
    const existing = await em.findOne(Post, { title: data.title });
    if (existing) {
      console.log(`- Post already exists: ${data.title}`);
      return existing;
    }

    const post = em.create(Post, {
      title: data.title,
      slug: '', // Auto-generated by hook usually, but let's confirm. Entity has hook? Yes.
      excerpt: data.excerpt,
      content: data.content,
      author: data.author,
      isActive: true, // Assuming isActive means "not deleted" and isPublished controls visibility
      isPublished: data.isPublished,
      publishedAt: data.publishedAt,
      viewCount: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    for (const topic of data.topics) post.topics.add(topic);
    for (const tag of data.tags) post.tags.add(tag);

    em.persist(post);
    console.log(`✓ Created post: ${data.title}`);
    return post;
  }
}
