// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AppGetHelloData,
  AppGetHelloResponses,
  AuthGetProfileData,
  AuthGetProfileResponses,
  AuthLoginData,
  AuthLoginResponses,
  CacheViewerClearAllData,
  CacheViewerClearAllResponses,
  CacheViewerDeleteKeyData,
  CacheViewerDeleteKeyResponses,
  CacheViewerGetKeysData,
  CacheViewerGetKeysResponses,
  CacheViewerGetValueData,
  CacheViewerGetValueResponses,
  CategoriesCreateData,
  CategoriesCreateResponses,
  CategoriesFindAllData,
  CategoriesFindAllResponses,
  CategoriesFindOneData,
  CategoriesFindOneErrors,
  CategoriesFindOneResponses,
  CategoriesFindTreeData,
  CategoriesFindTreeResponses,
  CategoriesRemoveData,
  CategoriesRemoveErrors,
  CategoriesRemoveImageData,
  CategoriesRemoveImageResponses,
  CategoriesRemoveResponses,
  CategoriesUpdateData,
  CategoriesUpdateErrors,
  CategoriesUpdateResponses,
  CategoriesUploadImageData,
  CategoriesUploadImageResponses,
  CustomersCreateData,
  CustomersCreateResponses,
  CustomersFindAllData,
  CustomersFindAllResponses,
  CustomersFindOneData,
  CustomersFindOneResponses,
  CustomersRemoveData,
  CustomersRemoveResponses,
  CustomersUpdateData,
  CustomersUpdateResponses,
  DashboardGetStatsData,
  DashboardGetStatsResponses,
  EmCampaignCancelData,
  EmCampaignCancelResponses,
  EmCampaignCreateData,
  EmCampaignCreateResponses,
  EmCampaignFindAllData,
  EmCampaignFindAllResponses,
  EmCampaignFindOneData,
  EmCampaignFindOneResponses,
  EmCampaignGetLogsData,
  EmCampaignGetLogsResponses,
  EmCampaignRemoveData,
  EmCampaignRemoveResponses,
  EmCampaignScheduleData,
  EmCampaignScheduleResponses,
  EmCampaignSendTestData,
  EmCampaignSendTestResponses,
  EmCampaignUpdateData,
  EmCampaignUpdateResponses,
  EmConfigFindAllData,
  EmConfigFindAllResponses,
  EmConfigSendTestData,
  EmConfigSendTestResponses,
  EmConfigUpdateBatchData,
  EmConfigUpdateBatchResponses,
  EmContactCreateData,
  EmContactCreateResponses,
  EmContactFindAllData,
  EmContactFindAllResponses,
  EmContactFindOneData,
  EmContactFindOneResponses,
  EmContactImportCsvData,
  EmContactImportCsvResponses,
  EmContactRemoveData,
  EmContactRemoveResponses,
  EmContactUpdateData,
  EmContactUpdateResponses,
  EmSegmentAssignContactsData,
  EmSegmentAssignContactsResponses,
  EmSegmentCreateData,
  EmSegmentCreateResponses,
  EmSegmentFindAllData,
  EmSegmentFindAllResponses,
  EmSegmentFindOneData,
  EmSegmentFindOneResponses,
  EmSegmentRemoveContactsData,
  EmSegmentRemoveContactsResponses,
  EmSegmentRemoveData,
  EmSegmentRemoveResponses,
  EmSegmentUpdateData,
  EmSegmentUpdateResponses,
  EmTemplateCreateData,
  EmTemplateCreateResponses,
  EmTemplateDuplicateData,
  EmTemplateDuplicateResponses,
  EmTemplateFindAllData,
  EmTemplateFindAllResponses,
  EmTemplateFindOneData,
  EmTemplateFindOneResponses,
  EmTemplatePreviewData,
  EmTemplatePreviewResponses,
  EmTemplateRemoveData,
  EmTemplateRemoveResponses,
  EmTemplateSendTestData,
  EmTemplateSendTestResponses,
  EmTemplateUpdateData,
  EmTemplateUpdateResponses,
  EmTrackingTrackClickData,
  EmTrackingTrackClickResponses,
  EmTrackingTrackOpenData,
  EmTrackingTrackOpenResponses,
  EmTrackingUnsubscribeData,
  EmTrackingUnsubscribeResponses,
  FaqsCreateData,
  FaqsCreateResponses,
  FaqsFindAllAdminData,
  FaqsFindAllAdminResponses,
  FaqsFindAllPublicData,
  FaqsFindAllPublicResponses,
  FaqsFindOneData,
  FaqsFindOneErrors,
  FaqsFindOneResponses,
  FaqsRemoveData,
  FaqsRemoveErrors,
  FaqsRemoveResponses,
  FaqsUpdateData,
  FaqsUpdateErrors,
  FaqsUpdateResponses,
  OrdersCreateData,
  OrdersCreateResponses,
  OrdersFindAllData,
  OrdersFindAllResponses,
  OrdersFindByCodeData,
  OrdersFindByCodeResponses,
  OrdersFindOneData,
  OrdersFindOneResponses,
  OrdersRemoveData,
  OrdersRemoveResponses,
  OrdersUpdateData,
  OrdersUpdateResponses,
  PagesCreateData,
  PagesCreateErrors,
  PagesCreateResponses,
  PagesFindAllData,
  PagesFindAllResponses,
  PagesFindBySlugData,
  PagesFindBySlugErrors,
  PagesFindBySlugResponses,
  PagesFindOneData,
  PagesFindOneErrors,
  PagesFindOneResponses,
  PagesRemoveData,
  PagesRemoveErrors,
  PagesRemoveResponses,
  PagesUpdateData,
  PagesUpdateErrors,
  PagesUpdateResponses,
  PermissionAllRolesData,
  PermissionAllRolesResponses,
  PermissionAssignPermissionData,
  PermissionAssignPermissionResponses,
  PermissionAssignPermissionsToGroupData,
  PermissionAssignPermissionsToGroupResponses,
  PermissionCreateData,
  PermissionCreatePermissionData,
  PermissionCreatePermissionGroupData,
  PermissionCreatePermissionGroupResponses,
  PermissionCreatePermissionResponses,
  PermissionCreateResponses,
  PermissionDeletePermissionData,
  PermissionDeletePermissionGroupData,
  PermissionDeletePermissionGroupResponses,
  PermissionDeletePermissionResponses,
  PermissionDeleteRoleData,
  PermissionDeleteRoleResponses,
  PermissionGetAllPermissionGroupsData,
  PermissionGetAllPermissionGroupsResponses,
  PermissionGetAllPermissionsData,
  PermissionGetAllPermissionsResponses,
  PermissionGetGroupedPermissionsData,
  PermissionGetGroupedPermissionsResponses,
  PermissionGetUserPermissionsData,
  PermissionGetUserPermissionsResponses,
  PermissionRemovePermissionFromRoleData,
  PermissionRemovePermissionFromRoleResponses,
  PermissionRemovePermissionsFromGroupData,
  PermissionRemovePermissionsFromGroupResponses,
  PermissionRoleDetailData,
  PermissionRoleDetailResponses,
  PermissionUpdatePermissionData,
  PermissionUpdatePermissionGroupData,
  PermissionUpdatePermissionGroupResponses,
  PermissionUpdatePermissionResponses,
  PermissionUpdateRoleData,
  PermissionUpdateRoleResponses,
  PopupsCreateData,
  PopupsCreateResponses,
  PopupsFindActiveData,
  PopupsFindActiveResponses,
  PopupsFindAllData,
  PopupsFindAllResponses,
  PopupsFindOneData,
  PopupsFindOneErrors,
  PopupsFindOneResponses,
  PopupsRemoveData,
  PopupsRemoveErrors,
  PopupsRemoveResponses,
  PopupsUpdateData,
  PopupsUpdateErrors,
  PopupsUpdateResponses,
  PostsCreateData,
  PostsCreateResponses,
  PostsFindAllData,
  PostsFindAllResponses,
  PostsFindOneData,
  PostsFindOneErrors,
  PostsFindOneResponses,
  PostsPublishData,
  PostsPublishResponses,
  PostsRemoveData,
  PostsRemoveErrors,
  PostsRemoveResponses,
  PostsRemoveThumbnailData,
  PostsRemoveThumbnailResponses,
  PostsScheduleData,
  PostsScheduleResponses,
  PostsUpdateData,
  PostsUpdateErrors,
  PostsUpdateResponses,
  PostsUploadThumbnailData,
  PostsUploadThumbnailResponses,
  ProductsAddVideoData,
  ProductsAddVideoResponses,
  ProductsCreateData,
  ProductsCreateResponses,
  ProductsDeleteImageData,
  ProductsDeleteImageResponses,
  ProductsDeleteVideoData,
  ProductsDeleteVideoResponses,
  ProductsFindAllData,
  ProductsFindAllResponses,
  ProductsFindBySlugData,
  ProductsFindBySlugErrors,
  ProductsFindBySlugResponses,
  ProductsFindOneData,
  ProductsFindOneErrors,
  ProductsFindOneResponses,
  ProductsRemoveData,
  ProductsRemoveErrors,
  ProductsRemoveResponses,
  ProductsReorderImagesData,
  ProductsReorderImagesResponses,
  ProductsUpdateData,
  ProductsUpdateDisplayOrderData,
  ProductsUpdateDisplayOrderResponses,
  ProductsUpdateErrors,
  ProductsUpdateImagesData,
  ProductsUpdateImagesResponses,
  ProductsUpdateResponses,
  ProductsUpdateSeoData,
  ProductsUpdateSeoResponses,
  ProductsUpdateVariantsData,
  ProductsUpdateVariantsResponses,
  ProductsUpdateVideoVisibilityData,
  ProductsUpdateVideoVisibilityResponses,
  ReviewsCreateData,
  ReviewsCreateResponses,
  ReviewsFindAllData,
  ReviewsFindAllResponses,
  ReviewsRemoveData,
  ReviewsRemoveResponses,
  SettingsCreateData,
  SettingsCreateErrors,
  SettingsCreateResponses,
  SettingsFindAllData,
  SettingsFindAllResponses,
  SettingsFindOneData,
  SettingsFindOneErrors,
  SettingsFindOneResponses,
  SettingsGetPublicSettingsData,
  SettingsGetPublicSettingsResponses,
  SettingsRemoveData,
  SettingsRemoveErrors,
  SettingsRemoveResponses,
  SettingsUpdateData,
  SettingsUpdateErrors,
  SettingsUpdateResponses,
  TagsCreateData,
  TagsCreateResponses,
  TagsFindAllData,
  TagsFindAllResponses,
  TagsFindOneData,
  TagsFindOneErrors,
  TagsFindOneResponses,
  TagsRemoveData,
  TagsRemoveErrors,
  TagsRemoveResponses,
  TagsUpdateData,
  TagsUpdateErrors,
  TagsUpdateResponses,
  TierVariationsApplyToAllVariantsData,
  TierVariationsApplyToAllVariantsErrors,
  TierVariationsApplyToAllVariantsResponses,
  TierVariationsBulkUpdateVariantsData,
  TierVariationsBulkUpdateVariantsErrors,
  TierVariationsBulkUpdateVariantsResponses,
  TierVariationsGenerateVariantsData,
  TierVariationsGenerateVariantsErrors,
  TierVariationsGenerateVariantsResponses,
  TierVariationsGetTierVariationsData,
  TierVariationsGetTierVariationsErrors,
  TierVariationsGetTierVariationsResponses,
  TierVariationsSetTierVariationsData,
  TierVariationsSetTierVariationsErrors,
  TierVariationsSetTierVariationsResponses,
  TopicsCreateData,
  TopicsCreateResponses,
  TopicsFindAllData,
  TopicsFindAllResponses,
  TopicsFindOneData,
  TopicsFindOneErrors,
  TopicsFindOneResponses,
  TopicsFindTreeData,
  TopicsFindTreeResponses,
  TopicsRemoveData,
  TopicsRemoveErrors,
  TopicsRemoveResponses,
  TopicsUpdateData,
  TopicsUpdateErrors,
  TopicsUpdateResponses,
  UploadUploadFileData,
  UploadUploadFileResponses,
  UploadUploadFromUrlData,
  UploadUploadFromUrlResponses,
  UserChangePasswordData,
  UserChangePasswordResponses,
  UserCreateData,
  UserCreateResponses,
  UserDeleteData,
  UserDeleteResponses,
  UserFindAllData,
  UserFindAllResponses,
  UserFindOneData,
  UserFindOneResponses,
  UserGetUserWithPermissionsData,
  UserGetUserWithPermissionsResponses,
  UserRegisterData,
  UserRegisterResponses,
  UserUpdateAvatarData,
  UserUpdateAvatarResponses,
  UserUpdateBackgroundData,
  UserUpdateBackgroundResponses,
  UserUpdateData,
  UserUpdateProfileData,
  UserUpdateProfileResponses,
  UserUpdateResponses,
  UserUpdateUserRoleData,
  UserUpdateUserRoleResponses,
  WebhooksCreateData,
  WebhooksCreateResponses,
  WebhooksFindAllData,
  WebhooksFindAllResponses,
  WebhooksFindOneData,
  WebhooksFindOneErrors,
  WebhooksFindOneResponses,
  WebhooksRemoveData,
  WebhooksRemoveErrors,
  WebhooksRemoveResponses,
  WebhooksUpdateData,
  WebhooksUpdateErrors,
  WebhooksUpdateResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Hello app
 */
export const appGetHello = <ThrowOnError extends boolean = false>(
  options?: Options<AppGetHelloData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AppGetHelloResponses, unknown, ThrowOnError>({
    url: '/api/v1',
    ...options,
  });

/**
 * Register a new user
 */
export const userRegister = <ThrowOnError extends boolean = false>(
  options: Options<UserRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<UserRegisterResponses, unknown, ThrowOnError>({
    url: '/api/v1/users/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update user profile
 */
export const userUpdateProfile = <ThrowOnError extends boolean = false>(
  options: Options<UserUpdateProfileData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UserUpdateProfileResponses, unknown, ThrowOnError>({
    url: '/api/v1/users/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update user avatar
 */
export const userUpdateAvatar = <ThrowOnError extends boolean = false>(
  options: Options<UserUpdateAvatarData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UserUpdateAvatarResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/users/profile/avatar',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Update user background
 */
export const userUpdateBackground = <ThrowOnError extends boolean = false>(
  options: Options<UserUpdateBackgroundData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UserUpdateBackgroundResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/users/profile/background',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Change password
 */
export const userChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<UserChangePasswordData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UserChangePasswordResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/change-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all users (Admin)
 */
export const userFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UserFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UserFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users',
    ...options,
  });

/**
 * Create user (Admin)
 */
export const userCreate = <ThrowOnError extends boolean = false>(
  options: Options<UserCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<UserCreateResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Delete user
 */
export const userDelete = <ThrowOnError extends boolean = false>(
  options: Options<UserDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<UserDeleteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options,
  });

/**
 * Get user by ID
 */
export const userFindOne = <ThrowOnError extends boolean = false>(
  options: Options<UserFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<UserFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options,
  });

/**
 * Update user (Admin)
 */
export const userUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UserUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UserUpdateResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Update user role
 */
export const userUpdateUserRole = <ThrowOnError extends boolean = false>(
  options: Options<UserUpdateUserRoleData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UserUpdateUserRoleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get user with permissions
 */
export const userGetUserWithPermissions = <ThrowOnError extends boolean = false>(
  options: Options<UserGetUserWithPermissionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<UserGetUserWithPermissionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}/permissions',
    ...options,
  });

/**
 * Login to the application
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLoginResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get user profile
 */
export const authGetProfile = <ThrowOnError extends boolean = false>(
  options?: Options<AuthGetProfileData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuthGetProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/profile',
    ...options,
  });

/**
 * Tải file trực tiếp lên hệ thống
 */
export const uploadUploadFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadUploadFileData, ThrowOnError>,
) =>
  (options.client ?? client).post<UploadUploadFileResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/upload/file',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Tải file từ URL về hệ thống
 */
export const uploadUploadFromUrl = <ThrowOnError extends boolean = false>(
  options: Options<UploadUploadFromUrlData, ThrowOnError>,
) =>
  (options.client ?? client).post<UploadUploadFromUrlResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/upload/url',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lấy danh sách sản phẩm
 */
export const productsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<ProductsFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ProductsFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/products',
    ...options,
  });

/**
 * Thêm mới sản phẩm (General Info)
 */
export const productsCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<ProductsCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Xóa sản phẩm
 */
export const productsRemove = <ThrowOnError extends boolean = false>(
  options: Options<ProductsRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<ProductsRemoveResponses, ProductsRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}',
    ...options,
  });

/**
 * Lấy chi tiết sản phẩm
 */
export const productsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<ProductsFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<ProductsFindOneResponses, ProductsFindOneErrors, ThrowOnError>({
    url: '/api/v1/products/{id}',
    ...options,
  });

/**
 * Cập nhật thông tin chung sản phẩm
 */
export const productsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<ProductsUpdateResponses, ProductsUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lấy chi tiết sản phẩm theo slug (Deprecated)
 */
export const productsFindBySlug = <ThrowOnError extends boolean = false>(
  options: Options<ProductsFindBySlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ProductsFindBySlugResponses,
    ProductsFindBySlugErrors,
    ThrowOnError
  >({ url: '/api/v1/products/slug/{slug}', ...options });

/**
 * Sắp xếp thứ tự hiển thị sản phẩm
 */
export const productsUpdateDisplayOrder = <ThrowOnError extends boolean = false>(
  options: Options<ProductsUpdateDisplayOrderData, ThrowOnError>,
) =>
  (options.client ?? client).post<ProductsUpdateDisplayOrderResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/display-order',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Cập nhật hình ảnh sản phẩm
 */
export const productsUpdateImages = <ThrowOnError extends boolean = false>(
  options: Options<ProductsUpdateImagesData, ThrowOnError>,
) =>
  (options.client ?? client).post<ProductsUpdateImagesResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/images',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Thêm video cho sản phẩm
 */
export const productsAddVideo = <ThrowOnError extends boolean = false>(
  options: Options<ProductsAddVideoData, ThrowOnError>,
) =>
  (options.client ?? client).post<ProductsAddVideoResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/videos',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Sắp xếp hình ảnh sản phẩm
 */
export const productsReorderImages = <ThrowOnError extends boolean = false>(
  options: Options<ProductsReorderImagesData, ThrowOnError>,
) =>
  (options.client ?? client).put<ProductsReorderImagesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/images/order',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Xóa hình ảnh sản phẩm
 */
export const productsDeleteImage = <ThrowOnError extends boolean = false>(
  options: Options<ProductsDeleteImageData, ThrowOnError>,
) =>
  (options.client ?? client).delete<ProductsDeleteImageResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/images/{imageId}',
    ...options,
  });

/**
 * Xóa video sản phẩm
 */
export const productsDeleteVideo = <ThrowOnError extends boolean = false>(
  options: Options<ProductsDeleteVideoData, ThrowOnError>,
) =>
  (options.client ?? client).delete<ProductsDeleteVideoResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/videos/{videoId}',
    ...options,
  });

/**
 * Cập nhật trạng thái hiển thị video
 */
export const productsUpdateVideoVisibility = <ThrowOnError extends boolean = false>(
  options: Options<ProductsUpdateVideoVisibilityData, ThrowOnError>,
) =>
  (options.client ?? client).patch<ProductsUpdateVideoVisibilityResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/videos/{videoId}/visibility',
    ...options,
  });

/**
 * Cập nhật biến thể sản phẩm
 */
export const productsUpdateVariants = <ThrowOnError extends boolean = false>(
  options: Options<ProductsUpdateVariantsData, ThrowOnError>,
) =>
  (options.client ?? client).put<ProductsUpdateVariantsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/variants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Cập nhật SEO sản phẩm
 */
export const productsUpdateSeo = <ThrowOnError extends boolean = false>(
  options: Options<ProductsUpdateSeoData, ThrowOnError>,
) =>
  (options.client ?? client).put<ProductsUpdateSeoResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/seo',
    ...options,
  });

/**
 * Lấy tier variations của sản phẩm
 */
export const tierVariationsGetTierVariations = <ThrowOnError extends boolean = false>(
  options: Options<TierVariationsGetTierVariationsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TierVariationsGetTierVariationsResponses,
    TierVariationsGetTierVariationsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/tier-variations',
    ...options,
  });

/**
 * Thiết lập tier variations cho sản phẩm
 *
 *
 * Thiết lập các phân loại hàng (tier variations) cho sản phẩm theo kiểu Shopee/TikTok.
 *
 * Ví dụ:
 * - Tier 1: Màu sắc [Đỏ, Xanh, Vàng]
 * - Tier 2: Kích thước [S, M, L, XL]
 *
 * Sau khi thiết lập, hệ thống sẽ tự động tạo variant matrix (Đỏ-S, Đỏ-M, ...).
 *
 */
export const tierVariationsSetTierVariations = <ThrowOnError extends boolean = false>(
  options: Options<TierVariationsSetTierVariationsData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    TierVariationsSetTierVariationsResponses,
    TierVariationsSetTierVariationsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/tier-variations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Tự động tạo variant matrix
 *
 *
 * Tạo lại variant matrix từ các tier options hiện có.
 * Các variants cũ sẽ bị xóa và tạo lại với giá/tồn kho mặc định.
 *
 */
export const tierVariationsGenerateVariants = <ThrowOnError extends boolean = false>(
  options: Options<TierVariationsGenerateVariantsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TierVariationsGenerateVariantsResponses,
    TierVariationsGenerateVariantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/generate-variants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Bulk update nhiều variants cùng lúc
 *
 * Cập nhật giá, tồn kho, SKU cho nhiều variants trong một request
 */
export const tierVariationsBulkUpdateVariants = <ThrowOnError extends boolean = false>(
  options: Options<TierVariationsBulkUpdateVariantsData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    TierVariationsBulkUpdateVariantsResponses,
    TierVariationsBulkUpdateVariantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/variants/bulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Áp dụng giá/tồn kho cho tất cả variants
 *
 * Đặt cùng giá, giá KM, hoặc tồn kho cho tất cả variants của sản phẩm
 */
export const tierVariationsApplyToAllVariants = <ThrowOnError extends boolean = false>(
  options: Options<TierVariationsApplyToAllVariantsData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    TierVariationsApplyToAllVariantsResponses,
    TierVariationsApplyToAllVariantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/products/{id}/variants/apply-all',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all categories
 */
export const categoriesFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<CategoriesFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CategoriesFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/categories',
    ...options,
  });

/**
 * Create a new category
 */
export const categoriesCreate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<CategoriesCreateResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/categories',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get category tree structure
 */
export const categoriesFindTree = <ThrowOnError extends boolean = false>(
  options?: Options<CategoriesFindTreeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CategoriesFindTreeResponses, unknown, ThrowOnError>({
    url: '/api/v1/categories/tree',
    ...options,
  });

/**
 * Delete a category
 */
export const categoriesRemove = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CategoriesRemoveResponses,
    CategoriesRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/categories/{id}',
    ...options,
  });

/**
 * Get category by ID
 */
export const categoriesFindOne = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<CategoriesFindOneResponses, CategoriesFindOneErrors, ThrowOnError>(
    { url: '/api/v1/categories/{id}', ...options },
  );

/**
 * Update a category
 */
export const categoriesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<CategoriesUpdateResponses, CategoriesUpdateErrors, ThrowOnError>(
    {
      ...formDataBodySerializer,
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/categories/{id}',
      ...options,
      headers: {
        'Content-Type': null,
        ...options.headers,
      },
    },
  );

/**
 * Remove category image
 */
export const categoriesRemoveImage = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesRemoveImageData, ThrowOnError>,
) =>
  (options.client ?? client).delete<CategoriesRemoveImageResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/categories/{id}/image',
    ...options,
  });

/**
 * Upload category image
 */
export const categoriesUploadImage = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesUploadImageData, ThrowOnError>,
) =>
  (options.client ?? client).post<CategoriesUploadImageResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/categories/{id}/image',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get all topics
 */
export const topicsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<TopicsFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<TopicsFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/topics',
    ...options,
  });

/**
 * Create a new topic
 */
export const topicsCreate = <ThrowOnError extends boolean = false>(
  options: Options<TopicsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<TopicsCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/topics',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get topic tree structure
 */
export const topicsFindTree = <ThrowOnError extends boolean = false>(
  options?: Options<TopicsFindTreeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<TopicsFindTreeResponses, unknown, ThrowOnError>({
    url: '/api/v1/topics/tree',
    ...options,
  });

/**
 * Delete a topic
 */
export const topicsRemove = <ThrowOnError extends boolean = false>(
  options: Options<TopicsRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<TopicsRemoveResponses, TopicsRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/topics/{id}',
    ...options,
  });

/**
 * Get topic by ID
 */
export const topicsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<TopicsFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<TopicsFindOneResponses, TopicsFindOneErrors, ThrowOnError>({
    url: '/api/v1/topics/{id}',
    ...options,
  });

/**
 * Update a topic
 */
export const topicsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TopicsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<TopicsUpdateResponses, TopicsUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/topics/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all posts with comprehensive filters
 *
 * Supports search, multi-topic/tag, slug, author, status, date ranges (published & created), view count range, thumbnail check, and flexible sorting.
 */
export const postsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<PostsFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PostsFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/posts',
    ...options,
  });

/**
 * Create a new post
 */
export const postsCreate = <ThrowOnError extends boolean = false>(
  options: Options<PostsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostsCreateResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get post by ID
 */
export const postsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<PostsFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<PostsFindOneResponses, PostsFindOneErrors, ThrowOnError>({
    url: '/api/v1/posts/{idOrSlug}',
    ...options,
  });

/**
 * Delete a post
 */
export const postsRemove = <ThrowOnError extends boolean = false>(
  options: Options<PostsRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<PostsRemoveResponses, PostsRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}',
    ...options,
  });

/**
 * Update a post
 */
export const postsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PostsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PostsUpdateResponses, PostsUpdateErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Publish a post immediately
 */
export const postsPublish = <ThrowOnError extends boolean = false>(
  options: Options<PostsPublishData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostsPublishResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}/publish',
    ...options,
  });

/**
 * Schedule a post for future publication
 */
export const postsSchedule = <ThrowOnError extends boolean = false>(
  options: Options<PostsScheduleData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostsScheduleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}/schedule',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove post thumbnail
 */
export const postsRemoveThumbnail = <ThrowOnError extends boolean = false>(
  options: Options<PostsRemoveThumbnailData, ThrowOnError>,
) =>
  (options.client ?? client).delete<PostsRemoveThumbnailResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}/thumbnail',
    ...options,
  });

/**
 * Upload post thumbnail
 */
export const postsUploadThumbnail = <ThrowOnError extends boolean = false>(
  options: Options<PostsUploadThumbnailData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostsUploadThumbnailResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}/thumbnail',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get all tags
 */
export const tagsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<TagsFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<TagsFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/tags',
    ...options,
  });

/**
 * Create a new tag
 */
export const tagsCreate = <ThrowOnError extends boolean = false>(
  options: Options<TagsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<TagsCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tags',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a tag
 */
export const tagsRemove = <ThrowOnError extends boolean = false>(
  options: Options<TagsRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<TagsRemoveResponses, TagsRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tags/{id}',
    ...options,
  });

/**
 * Get tag by ID
 */
export const tagsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<TagsFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<TagsFindOneResponses, TagsFindOneErrors, ThrowOnError>({
    url: '/api/v1/tags/{id}',
    ...options,
  });

/**
 * Update a tag
 */
export const tagsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TagsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<TagsUpdateResponses, TagsUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tags/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all popups
 */
export const popupsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<PopupsFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PopupsFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/popups',
    ...options,
  });

/**
 * Create a new popup
 */
export const popupsCreate = <ThrowOnError extends boolean = false>(
  options: Options<PopupsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<PopupsCreateResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/popups',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get active popup for client
 */
export const popupsFindActive = <ThrowOnError extends boolean = false>(
  options?: Options<PopupsFindActiveData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PopupsFindActiveResponses, unknown, ThrowOnError>({
    url: '/api/v1/popups/active',
    ...options,
  });

/**
 * Delete a popup
 */
export const popupsRemove = <ThrowOnError extends boolean = false>(
  options: Options<PopupsRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<PopupsRemoveResponses, PopupsRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/popups/{id}',
    ...options,
  });

/**
 * Get popup by ID
 */
export const popupsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<PopupsFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<PopupsFindOneResponses, PopupsFindOneErrors, ThrowOnError>({
    url: '/api/v1/popups/{id}',
    ...options,
  });

/**
 * Update a popup
 */
export const popupsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PopupsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PopupsUpdateResponses, PopupsUpdateErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/popups/{id}',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Lấy tất cả cấu hình SMTP
 */
export const emConfigFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<EmConfigFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<EmConfigFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/config',
    ...options,
  });

/**
 * Cập nhật hàng loạt cấu hình SMTP
 */
export const emConfigUpdateBatch = <ThrowOnError extends boolean = false>(
  options: Options<EmConfigUpdateBatchData, ThrowOnError>,
) =>
  (options.client ?? client).put<EmConfigUpdateBatchResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/config',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Gửi email test với cấu hình SMTP hiện tại
 */
export const emConfigSendTest = <ThrowOnError extends boolean = false>(
  options: Options<EmConfigSendTestData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmConfigSendTestResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/config/test',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Danh sách contacts
 */
export const emContactFindAll = <ThrowOnError extends boolean = false>(
  options: Options<EmContactFindAllData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmContactFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/contacts',
    ...options,
  });

/**
 * Tạo contact
 */
export const emContactCreate = <ThrowOnError extends boolean = false>(
  options: Options<EmContactCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmContactCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/contacts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Xóa contact
 */
export const emContactRemove = <ThrowOnError extends boolean = false>(
  options: Options<EmContactRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<EmContactRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/contacts/{id}',
    ...options,
  });

/**
 * Chi tiết contact
 */
export const emContactFindOne = <ThrowOnError extends boolean = false>(
  options: Options<EmContactFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmContactFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/contacts/{id}',
    ...options,
  });

/**
 * Cập nhật contact
 */
export const emContactUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EmContactUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<EmContactUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/contacts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Import contacts từ CSV
 */
export const emContactImportCsv = <ThrowOnError extends boolean = false>(
  options: Options<EmContactImportCsvData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmContactImportCsvResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/contacts/import',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Danh sách segments
 */
export const emSegmentFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<EmSegmentFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<EmSegmentFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/segments',
    ...options,
  });

/**
 * Tạo segment
 */
export const emSegmentCreate = <ThrowOnError extends boolean = false>(
  options: Options<EmSegmentCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmSegmentCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/segments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Xóa segment
 */
export const emSegmentRemove = <ThrowOnError extends boolean = false>(
  options: Options<EmSegmentRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<EmSegmentRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/segments/{id}',
    ...options,
  });

/**
 * Chi tiết segment + contacts
 */
export const emSegmentFindOne = <ThrowOnError extends boolean = false>(
  options: Options<EmSegmentFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmSegmentFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/segments/{id}',
    ...options,
  });

/**
 * Cập nhật segment
 */
export const emSegmentUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EmSegmentUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<EmSegmentUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/segments/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Gỡ contacts khỏi segment
 */
export const emSegmentRemoveContacts = <ThrowOnError extends boolean = false>(
  options: Options<EmSegmentRemoveContactsData, ThrowOnError>,
) =>
  (options.client ?? client).delete<EmSegmentRemoveContactsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/segments/{id}/contacts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Gán contacts vào segment
 */
export const emSegmentAssignContacts = <ThrowOnError extends boolean = false>(
  options: Options<EmSegmentAssignContactsData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmSegmentAssignContactsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/segments/{id}/contacts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Danh sách templates
 */
export const emTemplateFindAll = <ThrowOnError extends boolean = false>(
  options: Options<EmTemplateFindAllData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmTemplateFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/templates',
    ...options,
  });

/**
 * Tạo template
 */
export const emTemplateCreate = <ThrowOnError extends boolean = false>(
  options: Options<EmTemplateCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmTemplateCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Xóa template
 */
export const emTemplateRemove = <ThrowOnError extends boolean = false>(
  options: Options<EmTemplateRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<EmTemplateRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/templates/{id}',
    ...options,
  });

/**
 * Chi tiết template (kèm designData)
 */
export const emTemplateFindOne = <ThrowOnError extends boolean = false>(
  options: Options<EmTemplateFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmTemplateFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/templates/{id}',
    ...options,
  });

/**
 * Cập nhật template
 */
export const emTemplateUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EmTemplateUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<EmTemplateUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/templates/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Preview template với sample data
 */
export const emTemplatePreview = <ThrowOnError extends boolean = false>(
  options: Options<EmTemplatePreviewData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmTemplatePreviewResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/templates/{id}/preview',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Nhân bản template
 */
export const emTemplateDuplicate = <ThrowOnError extends boolean = false>(
  options: Options<EmTemplateDuplicateData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmTemplateDuplicateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/templates/{id}/duplicate',
    ...options,
  });

/**
 * Gửi email test
 */
export const emTemplateSendTest = <ThrowOnError extends boolean = false>(
  options: Options<EmTemplateSendTestData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmTemplateSendTestResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/templates/{id}/send-test',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Danh sách campaigns
 */
export const emCampaignFindAll = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignFindAllData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmCampaignFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns',
    ...options,
  });

/**
 * Tạo campaign (DRAFT)
 */
export const emCampaignCreate = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmCampaignCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Xóa campaign (chỉ DRAFT/CANCELLED)
 */
export const emCampaignRemove = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<EmCampaignRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns/{id}',
    ...options,
  });

/**
 * Chi tiết campaign + stats
 */
export const emCampaignFindOne = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmCampaignFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns/{id}',
    ...options,
  });

/**
 * Cập nhật campaign
 */
export const emCampaignUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<EmCampaignUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Đặt lịch gửi campaign
 */
export const emCampaignSchedule = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignScheduleData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmCampaignScheduleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns/{id}/schedule',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Hủy campaign
 */
export const emCampaignCancel = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignCancelData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmCampaignCancelResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns/{id}/cancel',
    ...options,
  });

/**
 * Gửi email test
 */
export const emCampaignSendTest = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignSendTestData, ThrowOnError>,
) =>
  (options.client ?? client).post<EmCampaignSendTestResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns/{id}/send-test',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Danh sách email logs của campaign
 */
export const emCampaignGetLogs = <ThrowOnError extends boolean = false>(
  options: Options<EmCampaignGetLogsData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmCampaignGetLogsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/email-marketing/campaigns/{id}/logs',
    ...options,
  });

/**
 * Open pixel tracking (trả về ảnh 1x1 GIF)
 */
export const emTrackingTrackOpen = <ThrowOnError extends boolean = false>(
  options: Options<EmTrackingTrackOpenData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmTrackingTrackOpenResponses, unknown, ThrowOnError>({
    url: '/api/v1/em-tracking/open/{logId}.gif',
    ...options,
  });

/**
 * Click tracking (redirect 302 tới URL gốc)
 */
export const emTrackingTrackClick = <ThrowOnError extends boolean = false>(
  options: Options<EmTrackingTrackClickData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmTrackingTrackClickResponses, unknown, ThrowOnError>({
    url: '/api/v1/em-tracking/click/{hash}',
    ...options,
  });

/**
 * Unsubscribe contact
 */
export const emTrackingUnsubscribe = <ThrowOnError extends boolean = false>(
  options: Options<EmTrackingUnsubscribeData, ThrowOnError>,
) =>
  (options.client ?? client).get<EmTrackingUnsubscribeResponses, unknown, ThrowOnError>({
    url: '/api/v1/em-tracking/unsubscribe/{contactId}/{token}',
    ...options,
  });

/**
 * Get all roles
 */
export const permissionAllRoles = <ThrowOnError extends boolean = false>(
  options?: Options<PermissionAllRolesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PermissionAllRolesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles',
    ...options,
  });

/**
 * Create a role
 */
export const permissionCreate = <ThrowOnError extends boolean = false>(
  options: Options<PermissionCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<PermissionCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a role
 */
export const permissionDeleteRole = <ThrowOnError extends boolean = false>(
  options: Options<PermissionDeleteRoleData, ThrowOnError>,
) =>
  (options.client ?? client).delete<PermissionDeleteRoleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles/{id}',
    ...options,
  });

/**
 * Get Role Detail
 */
export const permissionRoleDetail = <ThrowOnError extends boolean = false>(
  options: Options<PermissionRoleDetailData, ThrowOnError>,
) =>
  (options.client ?? client).get<PermissionRoleDetailResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles/{id}',
    ...options,
  });

/**
 * Update a role
 */
export const permissionUpdateRole = <ThrowOnError extends boolean = false>(
  options: Options<PermissionUpdateRoleData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PermissionUpdateRoleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all permissions
 */
export const permissionGetAllPermissions = <ThrowOnError extends boolean = false>(
  options?: Options<PermissionGetAllPermissionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PermissionGetAllPermissionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permissions',
    ...options,
  });

/**
 * Create a permission
 */
export const permissionCreatePermission = <ThrowOnError extends boolean = false>(
  options: Options<PermissionCreatePermissionData, ThrowOnError>,
) =>
  (options.client ?? client).post<PermissionCreatePermissionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permissions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Assign permission to a role
 */
export const permissionAssignPermission = <ThrowOnError extends boolean = false>(
  options: Options<PermissionAssignPermissionData, ThrowOnError>,
) =>
  (options.client ?? client).post<PermissionAssignPermissionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles/{id}/permission',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a permission
 */
export const permissionDeletePermission = <ThrowOnError extends boolean = false>(
  options: Options<PermissionDeletePermissionData, ThrowOnError>,
) =>
  (options.client ?? client).delete<PermissionDeletePermissionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permissions/{id}',
    ...options,
  });

/**
 * Update a permission
 */
export const permissionUpdatePermission = <ThrowOnError extends boolean = false>(
  options: Options<PermissionUpdatePermissionData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PermissionUpdatePermissionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permissions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove permission from role
 */
export const permissionRemovePermissionFromRole = <ThrowOnError extends boolean = false>(
  options: Options<PermissionRemovePermissionFromRoleData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PermissionRemovePermissionFromRoleResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles/{roleId}/permissions/{permissionId}',
    ...options,
  });

/**
 * Get user permissions
 */
export const permissionGetUserPermissions = <ThrowOnError extends boolean = false>(
  options: Options<PermissionGetUserPermissionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<PermissionGetUserPermissionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{userId}/permissions',
    ...options,
  });

/**
 * Get grouped permissions
 */
export const permissionGetGroupedPermissions = <ThrowOnError extends boolean = false>(
  options?: Options<PermissionGetGroupedPermissionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PermissionGetGroupedPermissionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permissions/grouped',
    ...options,
  });

/**
 * Get all permission groups
 */
export const permissionGetAllPermissionGroups = <ThrowOnError extends boolean = false>(
  options?: Options<PermissionGetAllPermissionGroupsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PermissionGetAllPermissionGroupsResponses, unknown, ThrowOnError>(
    {
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/permission-groups',
      ...options,
    },
  );

/**
 * Create a permission group
 */
export const permissionCreatePermissionGroup = <ThrowOnError extends boolean = false>(
  options: Options<PermissionCreatePermissionGroupData, ThrowOnError>,
) =>
  (options.client ?? client).post<PermissionCreatePermissionGroupResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permission-groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a permission group
 */
export const permissionDeletePermissionGroup = <ThrowOnError extends boolean = false>(
  options: Options<PermissionDeletePermissionGroupData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PermissionDeletePermissionGroupResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permission-groups/{id}',
    ...options,
  });

/**
 * Update a permission group
 */
export const permissionUpdatePermissionGroup = <ThrowOnError extends boolean = false>(
  options: Options<PermissionUpdatePermissionGroupData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PermissionUpdatePermissionGroupResponses, unknown, ThrowOnError>(
    {
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/permission-groups/{id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    },
  );

/**
 * Remove permissions from a group
 */
export const permissionRemovePermissionsFromGroup = <ThrowOnError extends boolean = false>(
  options: Options<PermissionRemovePermissionsFromGroupData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PermissionRemovePermissionsFromGroupResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permission-groups/{id}/permissions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Assign permissions to a group
 */
export const permissionAssignPermissionsToGroup = <ThrowOnError extends boolean = false>(
  options: Options<PermissionAssignPermissionsToGroupData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PermissionAssignPermissionsToGroupResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/permission-groups/{id}/permissions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List all cache keys
 */
export const cacheViewerGetKeys = <ThrowOnError extends boolean = false>(
  options?: Options<CacheViewerGetKeysData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CacheViewerGetKeysResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/cache/keys',
    ...options,
  });

/**
 * Delete cache key
 */
export const cacheViewerDeleteKey = <ThrowOnError extends boolean = false>(
  options: Options<CacheViewerDeleteKeyData, ThrowOnError>,
) =>
  (options.client ?? client).delete<CacheViewerDeleteKeyResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/cache/keys/{key}',
    ...options,
  });

/**
 * Get cache value by key
 */
export const cacheViewerGetValue = <ThrowOnError extends boolean = false>(
  options: Options<CacheViewerGetValueData, ThrowOnError>,
) =>
  (options.client ?? client).get<CacheViewerGetValueResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/cache/keys/{key}',
    ...options,
  });

/**
 * Clear all cache
 */
export const cacheViewerClearAll = <ThrowOnError extends boolean = false>(
  options?: Options<CacheViewerClearAllData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<CacheViewerClearAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/cache/all',
    ...options,
  });

/**
 * Get all public FAQs
 */
export const faqsFindAllPublic = <ThrowOnError extends boolean = false>(
  options?: Options<FaqsFindAllPublicData, ThrowOnError>,
) =>
  (options?.client ?? client).get<FaqsFindAllPublicResponses, unknown, ThrowOnError>({
    url: '/api/v1/faqs',
    ...options,
  });

/**
 * Create FAQ
 */
export const faqsCreate = <ThrowOnError extends boolean = false>(
  options: Options<FaqsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<FaqsCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/faqs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all FAQs (Admin)
 */
export const faqsFindAllAdmin = <ThrowOnError extends boolean = false>(
  options?: Options<FaqsFindAllAdminData, ThrowOnError>,
) =>
  (options?.client ?? client).get<FaqsFindAllAdminResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/faqs/admin',
    ...options,
  });

/**
 * Delete FAQ
 */
export const faqsRemove = <ThrowOnError extends boolean = false>(
  options: Options<FaqsRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<FaqsRemoveResponses, FaqsRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/faqs/{id}',
    ...options,
  });

/**
 * Get FAQ by ID
 */
export const faqsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<FaqsFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<FaqsFindOneResponses, FaqsFindOneErrors, ThrowOnError>({
    url: '/api/v1/faqs/{id}',
    ...options,
  });

/**
 * Update FAQ
 */
export const faqsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<FaqsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<FaqsUpdateResponses, FaqsUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/faqs/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get page by slug (Public) - Deprecated
 */
export const pagesFindBySlug = <ThrowOnError extends boolean = false>(
  options: Options<PagesFindBySlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<PagesFindBySlugResponses, PagesFindBySlugErrors, ThrowOnError>({
    url: '/api/v1/pages/slug/{slug}',
    ...options,
  });

/**
 * Get all Pages (Public)
 */
export const pagesFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<PagesFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PagesFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/pages',
    ...options,
  });

/**
 * Create Page
 */
export const pagesCreate = <ThrowOnError extends boolean = false>(
  options: Options<PagesCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<PagesCreateResponses, PagesCreateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/pages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Page
 */
export const pagesRemove = <ThrowOnError extends boolean = false>(
  options: Options<PagesRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<PagesRemoveResponses, PagesRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/pages/{id}',
    ...options,
  });

/**
 * Get Page by ID or Slug
 */
export const pagesFindOne = <ThrowOnError extends boolean = false>(
  options: Options<PagesFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<PagesFindOneResponses, PagesFindOneErrors, ThrowOnError>({
    url: '/api/v1/pages/{id}',
    ...options,
  });

/**
 * Update Page
 */
export const pagesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PagesUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PagesUpdateResponses, PagesUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/pages/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get public settings
 */
export const settingsGetPublicSettings = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsGetPublicSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<SettingsGetPublicSettingsResponses, unknown, ThrowOnError>({
    url: '/api/v1/settings/public',
    ...options,
  });

/**
 * Get all Settings (Admin)
 */
export const settingsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<SettingsFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/settings',
    ...options,
  });

/**
 * Create Setting
 */
export const settingsCreate = <ThrowOnError extends boolean = false>(
  options: Options<SettingsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<SettingsCreateResponses, SettingsCreateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Setting
 */
export const settingsRemove = <ThrowOnError extends boolean = false>(
  options: Options<SettingsRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<SettingsRemoveResponses, SettingsRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/settings/{id}',
    ...options,
  });

/**
 * Get Setting by ID
 */
export const settingsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<SettingsFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<SettingsFindOneResponses, SettingsFindOneErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/settings/{id}',
    ...options,
  });

/**
 * Update Setting
 */
export const settingsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<SettingsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<SettingsUpdateResponses, SettingsUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/settings/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all reviews
 */
export const reviewsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<ReviewsFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ReviewsFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/reviews',
    ...options,
  });

/**
 * Create a new review
 */
export const reviewsCreate = <ThrowOnError extends boolean = false>(
  options: Options<ReviewsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReviewsCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/reviews',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a review
 */
export const reviewsRemove = <ThrowOnError extends boolean = false>(
  options: Options<ReviewsRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<ReviewsRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/reviews/{id}',
    ...options,
  });

/**
 * Lấy danh sách khách hàng
 */
export const customersFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<CustomersFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CustomersFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/customers',
    ...options,
  });

/**
 * Thêm khách hàng mới
 */
export const customersCreate = <ThrowOnError extends boolean = false>(
  options: Options<CustomersCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<CustomersCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/customers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Xóa khách hàng
 */
export const customersRemove = <ThrowOnError extends boolean = false>(
  options: Options<CustomersRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<CustomersRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/customers/{id}',
    ...options,
  });

/**
 * Lấy chi tiết khách hàng
 */
export const customersFindOne = <ThrowOnError extends boolean = false>(
  options: Options<CustomersFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<CustomersFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/customers/{id}',
    ...options,
  });

/**
 * Cập nhật khách hàng
 */
export const customersUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CustomersUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<CustomersUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/customers/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lấy danh sách đơn hàng
 */
export const ordersFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<OrdersFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<OrdersFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/orders',
    ...options,
  });

/**
 * Tạo đơn hàng mới
 */
export const ordersCreate = <ThrowOnError extends boolean = false>(
  options: Options<OrdersCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<OrdersCreateResponses, unknown, ThrowOnError>({
    url: '/api/v1/orders',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Xóa đơn hàng
 */
export const ordersRemove = <ThrowOnError extends boolean = false>(
  options: Options<OrdersRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<OrdersRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/orders/{id}',
    ...options,
  });

/**
 * Lấy chi tiết đơn hàng theo ID
 */
export const ordersFindOne = <ThrowOnError extends boolean = false>(
  options: Options<OrdersFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<OrdersFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/orders/{id}',
    ...options,
  });

/**
 * Cập nhật đơn hàng (trạng thái, thông tin khách, địa chỉ...)
 */
export const ordersUpdate = <ThrowOnError extends boolean = false>(
  options: Options<OrdersUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<OrdersUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/orders/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lấy đơn hàng theo mã
 */
export const ordersFindByCode = <ThrowOnError extends boolean = false>(
  options: Options<OrdersFindByCodeData, ThrowOnError>,
) =>
  (options.client ?? client).get<OrdersFindByCodeResponses, unknown, ThrowOnError>({
    url: '/api/v1/orders/code/{code}',
    ...options,
  });

/**
 * Get all webhooks
 */
export const webhooksFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<WebhooksFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<WebhooksFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/webhooks',
    ...options,
  });

/**
 * Create a new webhook
 */
export const webhooksCreate = <ThrowOnError extends boolean = false>(
  options: Options<WebhooksCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<WebhooksCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/webhooks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a webhook
 */
export const webhooksRemove = <ThrowOnError extends boolean = false>(
  options: Options<WebhooksRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<WebhooksRemoveResponses, WebhooksRemoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/webhooks/{id}',
    ...options,
  });

/**
 * Get a webhook by ID
 */
export const webhooksFindOne = <ThrowOnError extends boolean = false>(
  options: Options<WebhooksFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<WebhooksFindOneResponses, WebhooksFindOneErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/webhooks/{id}',
    ...options,
  });

/**
 * Update a webhook
 */
export const webhooksUpdate = <ThrowOnError extends boolean = false>(
  options: Options<WebhooksUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<WebhooksUpdateResponses, WebhooksUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/webhooks/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lấy thống kê tổng quan Dashboard
 */
export const dashboardGetStats = <ThrowOnError extends boolean = false>(
  options?: Options<DashboardGetStatsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<DashboardGetStatsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/dashboard/stats',
    ...options,
  });
