import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@mikro-orm/nestjs';
import { EntityManager, EntityRepository, FilterQuery } from '@mikro-orm/mysql';
import { Topic } from 'src/database/entities/topic.entity';
import { CreateTopicDto } from './dto/create-topic.dto';
import { UpdateTopicDto } from './dto/update-topic.dto';
import { TopicQueryDto } from './dto/topic-query.dto';

@Injectable()
export class TopicsService {
  constructor(
    @InjectRepository(Topic)
    private readonly topicRepository: EntityRepository<Topic>,
    private readonly em: EntityManager,
  ) {}

  async findAll(query: TopicQueryDto) {
    const {
      page = 1,
      limit = 10,
      search,
      parent_id,
      level,
      is_active,
      include_children = false,
      include_posts = false,
    } = query;
    const offset = (page - 1) * limit;

    const where: FilterQuery<Topic> = {};

    if (search) {
      where.$or = [
        { name: { $like: `%${search}%` } },
        { description: { $like: `%${search}%` } },
      ];
    }

    if (parent_id !== undefined) {
      where.parent = parent_id;
    }

    if (level !== undefined) {
      where.level = level;
    }

    if (is_active !== undefined) {
      where.isActive = is_active;
    }

    const populate: any[] = ['parent'];
    if (include_children) {
      populate.push('children');
    }
    if (include_posts) {
      populate.push('posts');
    }

    const [items, total] = await this.topicRepository.findAndCount(where, {
      limit,
      offset,
      populate,
      orderBy: { sortOrder: 'ASC', createdAt: 'DESC' },
    });

    return {
      items,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  async findOne(idOrSlug: number | string) {
    let topic;
    if (typeof idOrSlug === 'number' || /^\d+$/.test(String(idOrSlug))) {
      topic = await this.topicRepository.findOne(Number(idOrSlug), {
        populate: ['parent', 'children', 'posts'],
      });
    } else {
      topic = await this.topicRepository.findOne({ slug: String(idOrSlug) } as any, {
        populate: ['parent', 'children', 'posts'],
      });
    }

    if (!topic) {
      throw new NotFoundException(`Topic with ID/slug '${idOrSlug}' not found`);
    }

    return topic;
  }

  async findTree() {
    // Get all root topics (level 0)
    const rootTopics = await this.topicRepository.find(
      { parent: null, isActive: true },
      {
        populate: ['children', 'children.children'],
        orderBy: { sortOrder: 'ASC', name: 'ASC' },
      },
    );

    return rootTopics;
  }

  async create(dto: CreateTopicDto) {
    return await this.em.transactional(async (em) => {
      let level = 0;
      let parent: Topic | null = null;

      // Check if parent exists and validate level
      if (dto.parent_id) {
        parent = await em.findOne(Topic, dto.parent_id);
        if (!parent) {
          throw new NotFoundException(
            `Parent topic with ID ${dto.parent_id} not found`,
          );
        }

        level = parent.level + 1;

        // Enforce 3-level limit (0, 1, 2)
        if (level > 2) {
          throw new BadRequestException(
            'Topics are limited to 3 levels. Cannot create a topic under a level 2 topic.',
          );
        }
      }

      const topic = em.create(Topic, {
        name: dto.name,
        slug: '', // Will be auto-generated by entity hook
        description: dto.description,
        parent: parent,
        level: level,
        isActive: dto.is_active ?? true,
        sortOrder: dto.sort_order ?? 0,
        metaTitle: dto.meta_title,
        metaDescription: dto.meta_description,
        metaKeywords: dto.meta_keywords,
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      await em.persistAndFlush(topic);
      return topic;
    });
  }

  async update(id: number, dto: UpdateTopicDto) {
    return await this.em.transactional(async (em) => {
      const topic = await em.findOne(Topic, id);

      if (!topic) {
        throw new NotFoundException(`Topic with ID ${id} not found`);
      }

      // Check if parent exists and validate level
      if (dto.parent_id !== undefined) {
        if (dto.parent_id === id) {
          throw new BadRequestException('Topic cannot be its own parent');
        }

        if (dto.parent_id) {
          const parent = await em.findOne(Topic, dto.parent_id);
          if (!parent) {
            throw new NotFoundException(
              `Parent topic with ID ${dto.parent_id} not found`,
            );
          }

          const newLevel = parent.level + 1;
          if (newLevel > 2) {
            throw new BadRequestException(
              'Topics are limited to 3 levels. Cannot move topic under a level 2 topic.',
            );
          }

          topic.parent = parent;
          topic.level = newLevel;
        } else {
          topic.parent = undefined;
          topic.level = 0;
        }
      }

      // Update fields
      if (dto.name !== undefined) {
        topic.name = dto.name;
        topic.slug = ''; // Reset to trigger regeneration
      }
      if (dto.description !== undefined) topic.description = dto.description;
      if (dto.is_active !== undefined) topic.isActive = dto.is_active;
      if (dto.sort_order !== undefined) topic.sortOrder = dto.sort_order;
      if (dto.meta_title !== undefined) topic.metaTitle = dto.meta_title;
      if (dto.meta_description !== undefined)
        topic.metaDescription = dto.meta_description;
      if (dto.meta_keywords !== undefined)
        topic.metaKeywords = dto.meta_keywords;

      await em.flush();
      return topic;
    });
  }

  async remove(id: number) {
    const topic = await this.topicRepository.findOne(id, {
      populate: ['children', 'posts'],
    });

    if (!topic) {
      throw new NotFoundException(`Topic with ID ${id} not found`);
    }

    // Check if topic has children
    if (topic.children.length > 0) {
      throw new BadRequestException('Cannot delete topic with child topics');
    }

    await this.em.removeAndFlush(topic);
    return { success: true };
  }
}
